### ISSUE TITLE
Wrong db version in nn-20180830-001.sql files

### ISSUE THREAD

**Issue by milovanderlinden** [simplerisk/database#1]
In https://github.com/simplerisk/database/blob/master/simplerisk-en-20180830-001.sql the DB version is set to 20180814-001 which makes the healthcheck (http://localhost/admin/health_check.php) report an outdated database schema.

**Comment by jsokol** [comment]
Thank you Milo!  Good catch.  I've fixed the version information in the appropriate files.  You should be able to fix the health check issue by going to yourinstance/admin/upgrade.php and running the database upgrade script.  I've also added you to our SimpleRisk Contributors page at https://www.simplerisk.com/contributors to thank you for letting us know.
